# WERCKER_TELEGRAM_NOTIFIER_BOT_TOKEN="<token>"
# WERCKER_TELEGRAM_NOTIFIER_CHAT_ID="<chatid>"

# DEPLOY=1
WERCKER_RESULT="passed"
# WERCKER_TELEGRAM_NOTIFIER_NOTIFY_ON="passed"
# WERCKER_TELEGRAM_NOTIFIER_BRANCH=""

WERCKER_FAILED_STEP_DISPLAY_NAME="this-step"

WERCKER_DEPLOY_URL="https://link.to.url/"
WERCKER_DEPLOYTARGET_NAME="staging"

WERCKER_BUILD_URL="https://link.to.url/"

WERCKER_APPLICATION_NAME="some-app"
WERCKER_STARTED_BY="me"
WERCKER_GIT_BRANCH="my-branch"
WERCKER_STEP_TEMP=$TMPDIR

source run.sh